# first member is context_path for route relay, second member is the actual mapping
GET http://localhost:8000/member/member/count
Accept: application/json

###

POST http://localhost:8000/member/member/register
Content-Type: application/x-www-form-urlencoded

mobile=

###